  version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: .Dockerfile
    env_file: 
      - .env
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
  postgres:
    container_name: postgres
    env_file: 
      - .env
    image: postgres:14
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
volumes:
    db-data: